name: apple_watch_test
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  watch_connectivity: ^0.1.4

dev_dependencies:
  rexios_lints: ^5.0.0

flutter:
  uses-material-design: true
